### ISSUE TITLE
Port customization 

### ISSUE THREAD

**Issue by PB0-Foxy** [UOAF/project-tauntaun#100]
Is it possible to have an option to customize the port we want to use with tauntaun ?
For some reason my new internet provider don't want me to forward port 8080

**Comment by adamdoda** [comment]
I will look into it but it's not trivial as the web client is pre-built.

**Comment by adamdoda** [comment]
Please verify it's working so I can close this ticket.
https://github.com/UOAF/project-tauntaun/wiki/Config-file
https://github.com/UOAF/project-tauntaun/actions/runs/1736026165

**Comment by PB0-Foxy** [comment]
It's working !
Thank you very much :)
