### ISSUE TITLE
no threat ring for SA-3 

### ISSUE THREAD

**Issue by PB0-Foxy** [UOAF/project-tauntaun#103]
Threat ring of the SA-3 doesn't show up on the map in build : 8723be2

I did place several SAM systems in a mission and where I don't have any problems with SA-2, SA-5 or SA-6 , the SA-3 doesn't show any threat ring on tauntaun map.
Tried to add a single SA-3 in a fresh mission just in case and I experienced the exact same problem.

**Comment by adamdoda** [comment]
Should be fixed in commit https://github.com/UOAF/project-tauntaun/actions/runs/1807988715
