### ISSUE TITLE
AGM-84 H SLAM-ER loadout option

### ISSUE THREAD

**Issue by The-Gargantuan** [UOAF/project-tauntaun#77]
This is a new feature as of [version 2.7.1.6430](https://www.digitalcombatsimulator.com/en/news/changelog/) - I did not notice it last Friday when the 107th last tested with [this build](https://github.com/UOAF/project-tauntaun/actions/runs/839624089)

**Comment by adamdoda** [comment]
Fixed in 39424a6462b7dce5873026264cf732f5b3f39c51
