### ISSUE TITLE
Hornet Loadout CMS Update

### ISSUE THREAD

**Issue by The-Gargantuan** [UOAF/project-tauntaun#79]
The hornet can now carry more flares with the recent DCS update

**Comment by adamdoda** [comment]
That was/is a fault in pydcs, it's generated from the game, it's unkown why isn't it correct.
I can try to hack around it in tauntaun.

**Comment by The-Gargantuan** [comment]
Eh, no need to hack around it - worse case we just have to rearm and change the cms only with the loadout already saved from tauntaun

**Comment by adamdoda** [comment]
Fixed in 39424a6
CMS "step size" is currently missing in pydcs (and probably it's not exported by DCS).
