### ISSUE TITLE
Missing pydcs requirement

### ISSUE THREAD

**Issue by gronank** [UOAF/project-tauntaun#97]
Installed requirement, ran pyinstaller, ran the tauntaun_live_editor.exe
Got the message of missing dcs.flyingunit.

I added pydcs==0.12.0 to the requirements file, redid the above steps and the exe runs fine.

**Comment by adamdoda** [comment]
Did you init/update submodules? pydcs is a submodule not an external requirement. 0.12 is way outdated.
